### ISSUE TITLE
Missing fields in childproc messages

### ISSUE THREAD

**Issue by jgajek** [carbonblack/cb-event-forwarder#107]
Childproc messages generated by the event-forwarder are missing some important fields:

1. The PID of the child process is not included in the generated JSON message (only the PID of the parent process is).

2. For suppressed child processes, the command line and user ID is not included in the JSON output -- as a result, there is no way to recover the full command-line of these processes from the raw event stream.

**Comment by mtmcgrew** [comment]
Including the commandline and username should be fixed in https://github.com/carbonblack/cb-event-forwarder/pull/110/files.

However, I am seeing that the PID of the child process is included. Do you have an example JSON message where the "pid" field is not present?

**Comment by jgajek** [comment]
Thanks for the response.  Here is an example of two childproc events with the same parent process.  You can see that the child_process_guids are different, but the pid field is the same.  That is because it is the pid of the parent process.  Child process pids are not included.  Taking a look at the relevant code in WriteChildProcMessage() (pb_message_processor.go) confirms that the child process pid is calculated and stored in the variable pid32, but not added to the key-value pairs for JSON output.

{"cb_server":"REDACTED","child_process_guid":"000000b1-0000-18a0-01d3-946a45592056","computer_name":"REDACTED","created":true,"event_type":"childproc","md5":"938A12B3104DD57A478BFF0F05336962","path":"c:\\windows\\system32\\searchfilterhost.exe","pid":9436,"process_guid":"000000b1-0000-24dc-01d3-93c33fe7907a","sensor_id":177,"sha256":"","timestamp":1516726227,"type":"ingress.event.childproc"}

{"cb_server":"REDACTED","child_process_guid":"000000b1-0000-1714-01d3-946a9957ed80","computer_name":"REDACTED","created":true,"event_type":"childproc","md5":"938A12B3104DD57A478BFF0F05336962","path":"c:\\windows\\system32\\searchfilterhost.exe","pid":9436,"process_guid":"000000b1-0000-24dc-01d3-93c33fe7907a","sensor_id":177,"sha256":"","timestamp":1516726368,"type":"ingress.event.childproc"}

**Comment by mtmcgrew** [comment]
Thanks for the extra info, that helps. 

The current `pid` field is populated in `ProcessProtobufMessage()` from the `CbHeaderMsg` protobuf message so that every event type has a `pid`.  https://github.com/carbonblack/cb-event-forwarder/blob/master/pb_message_processor.go#L319

It's possible that we should be using `CbProcessMetadataMsg` instead of `CbHeaderMsg`, or there is a product issue.

I'll defer to @jgarman

**Comment by jgajek** [comment]
It would be fine to leave the current parent pid field in -- just add a new child_proc_pid field with the relevant PID value for the child process.

**Comment by jgarman** [comment]
we should have all these fields accounted for here: https://github.com/carbonblack/cb-event-forwarder/commit/58c6ca52497f0984da1c3eaa8f20d1b2a689726b
