### ISSUE TITLE
using use_raw_sensor_exchange does not work

### ISSUE THREAD

**Issue by mtmcgrew** [carbonblack/cb-event-forwarder#116]
When setting `use_raw_sensor_exchange` to `true` and `events_raw_sensor` to `0` no sensor events are outputted. 

I confirmed this by adding a debug line to `ProcessRawZipBundle`

```
		msgs = append(msgs, newMsgs...)
	}
	log.Info(msgs)
	return msgs, nil
}
```

And I can see that a bunch of empty dicts are being returned
```
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
INFO[0112] []
```

Using only the `api.rawsensordata` exchange with a custom event forwarder is working in our environment. 

I would like to only subscribe to `api.rawsensordata` and not have to subscribe to all of the other ingress.* exchanges.

**Comment by jgarman** [comment]
You will need to include the `events_raw_sensor=ALL`. It will still try and subscribe to the individual event streams (this should be fixed, by the way, so we will mark this). However, your Cb Response server should not be publishing events once the `DatastoreBroadcastEventTypes` is commented out in `/etc/cb/cb.conf`
