### ISSUE TITLE
events_raw_sensor should default to 0 instead of ALL

### ISSUE THREAD

**Issue by dbrouss** [carbonblack/cb-event-forwarder#119]
https://github.com/carbonblack/cb-event-forwarder/blob/4a66527236fc7c53ac5c9f84dc3c84028a8203f1/conf/cb-event-forwarder.example.ini#L266

I believe it is extremely rare for any client to want all raw sensor events to be sent through the cb-event-forwarder.  The specific event types to forward from Cb Response is no longer configured in the cb.conf file, instead sending all sensor events compressed over the bus.  The issue becomes apparent when more than one forwarder is implemented, and the cb-event-forwarders send all data.  This happened to one of our clients in the Cb Response Cloud environment and this can have a significant impact on clients when the events are sent to a metered SIEM product.

Since it would be exceedingly rare for a client to send all sensor events out of the event forwarder, I suggest that the default should become 0, and the client is free to specify the event types they want to forward.   I spoke about this with Ryan at Carbon Black and he seems to agree with this assessment, so it may be of value to get his feedback as well.

**Comment by jgarman** [comment]
Agreed - we just changed this in revision 45bc84b190129dd64d6c60c4ec79737887a63242
