### ISSUE TITLE
Better handling of output types that are unavailable upon startup

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#124]
Right now, certain output types (network/tcp, syslog/tcp) will attempt to contact the remote endpoint when the `Initialize()` function is called. If the remote endpoint is not available when the event forwarder starts up, the event forwarder will immediately exit with an error condition.

Change the behavior so that the event forwarder will instead attempt to retry the remote endpoint (logging appropriate errors along the way)

**Comment by zacharyestep** [comment]
Handled for 4.0
