### ISSUE TITLE
Investigate persistent queues for certain event types

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#125]
Originally the event forwarder used non-persistent queues for performance reasons. With the advent of the raw sensor exchange (which vastly reduces the number of messages over the bus) as well as features in RabbitMQ to limit the maximum size of a persistent queue, we can revisit this design decision and provide better reliability.

**Comment by zacharyestep** [comment]
Message persistence is property of messages set at production time. Exposed configuration options in 4.0 for queue durability , allowing CbR EF to take advantages of any durable q available
