### ISSUE TITLE
Testing cb-event-forwarder in debug-mode 

### ISSUE THREAD

**Issue by vnagendra** [carbonblack/cb-event-forwarder#14]
`cb-event-forwarder` should be able to send a test `ping` or some kind of test message in `debug` mode. 

I tried a couple of integrations.. TCP, and S3

It is not clear whether the receiver isn't configured right or the sender isn't able to send. When the problem is DNS resolution, the logs (`/var/logs/cb/integrations**`) are pretty clear (in debug mode) - but when that's not the problem, there is no indication in the log file about what happened to the TCP packet. 

Same issue with S3, there is no indication in the log file where the process failed. In my testing, I enabled Cloudtrail, which showed no events to the bucket - which I suspect means there is some other issue on the sender's side

**Comment by jgarman** [comment]
Check out the new debug JSON output- hit http://<host>:33706/debug/vars when running the new 3.0.0 cb-event-forwarder and you will receive a host of debugging/monitoring metrics
