### ISSUE TITLE
Forward events from Cb Resonse Cloud to Splunk Cloud

### ISSUE THREAD

**Issue by rzzldzzl** [carbonblack/cb-event-forwarder#141]
It does not appear there that cb-event-forwarder will work with CbR Cloud as RabbitMQ is not exposed.  Is there a way to forward events from CbR Cloud to Splunk Cloud?

**Comment by jgarman** [comment]
The Cb Event Forwarder is installed on the Response Cloud server directly by our ops team. Open up a support ticket with Cb support containing your HTTP Event Collector information for Splunk Cloud and we will get the Event Forwarder configured for you. If you need any help please reach out to support and they'll get you taken care of.
