### ISSUE TITLE
Filtering by actions

### ISSUE THREAD

**Issue by chilichzfrito** [carbonblack/cb-event-forwarder#142]
For the following event types, we would like the ability to filter on the "action":
ingress.event.filemod
ingress.event.regmod

For scaling reasons in the cb-event-forwarder we'd like to only receive the following action types:
filemod: action="lastwrite"
regmod: action="createkey"

This is currently not possible since filtering of "filemod" and "regmod" types are all-or-nothing.  Need better granularity.

**Comment by zacharyestep** [comment]
This is a feature in the 4.0 base.
