### ISSUE TITLE
RHEL7 rpm not contained in the repositry

### ISSUE THREAD

**Issue by ThePhilderbeast** [carbonblack/cb-event-forwarder#145]
can I please have the RHEL7 compatible binaries access to the yum repo, currently the 3.5 version does not install on RHEL7 however the centos7 version on the release page does

**Comment by askthedragon** [comment]
Right now we are only distributing centos/rhel 6 rpms through our open source yum repository.  All RHEL7 rpms will be on github.  We are looking into potentially having a centos/rhel 7 yum repo soon.

**Comment by ThePhilderbeast** [comment]
sorry, not sure why this was closed, what you have described is exactly the issue I'm looking to get fixed here.

**Comment by zacharyestep** [comment]
Hey phillip - we're working on this. Issue got closed by accident! 
I've made the RPM available on the releases page ;-)

I have to do some infrastructure work to get things to push up to our github repository in an efficient manner. 

V/r,

ZE
