### ISSUE TITLE
Support multiple output types

### ISSUE THREAD

**Issue by vnagendra** [carbonblack/cb-event-forwarder#15]
In `event-forwarder.conf`, could we support multiple output types? 

Tried the following with no luck 
`output_type=tcp,s3, file` 
... With all the configurations for the options specified 

also tried a different variation with `output_type` specified in separate lines with their respective configurations specified, which (as suspected) didn't work either..

**Comment by jgarman** [comment]
For now I am recommending folks who need this functionality to run multiple instances of the event-forwarder. Multiple concurrent copies will create unique queues on the Cb server, so they will not interfere with each other.
