### ISSUE TITLE
cb event forwarder not sending event

### ISSUE THREAD

**Issue by austin-lai** [carbonblack/cb-event-forwarder#155]
Hi,

We try to forward cb response event to kiwi syslog, setup completed and cb event forwarder running fine even with the 33706 port web diagnostic is working fine.

However, we are unable to receive any log in our kiwi syslog.

We do configure cb event forwarder to forward log to kiwi syslog as below:
output_type=syslog
output_format=leef
syslogout=tcp:x.x.x.x:514

Can anyone help on this? not sure what issue being encounter

FYI, since not yet deploy in production.
We do turn off centos firewall and selinux.
cb event forwarder install on cb response server itself and both kiwi syslog and cb response are on the same subnet/flat network.

**Comment by jgarman** [comment]
Can you email support@carbonblack.com with the log messages from the event forwarder and the output from the web diagnostic port? We can try and troubleshoot with you directly. Thanks!
