### ISSUE TITLE
Event Forwarder Does not appear to include SHA256 Values for some fields

### ISSUE THREAD

**Issue by robsmallridge** [carbonblack/cb-event-forwarder#162]
I am currently testing the Event Forwarder being consumed by Splunk HEC. Looking at the fields for the Binary Observed Events, the SHA256 field is not being populated. 

Example of JSON log below: 

```
{	[-]	
  	 cb_server:	 cbserver	
  	 computer_name:	 [redacted]	
  	 hostname:	 [redacted]
  	 link_md5:	 https://cb.[redacted]/#/binary/[redacted]CF2EB2E0B	
  	 link_sensor:	 https://cb.[redacted]/#/host/16	
  	 md5:	[redacted]CF2EB2E0B	
  	 scores:	{	[+]	
  	}	
  	 sensor_id:	 16	
  	 sha256:	
  	 timestamp:	 1563267571.403	
  	 type:	 binaryinfo.host.observed	
  	 watchlists:	{	[+]	
  	}	
}
```

**Comment by zacharyestep** [comment]
This is symptomatic of the server not sending a sha256 in the cbeventmessage.module not some mishandling in the forwarder itself. Closing.
