### ISSUE TITLE
Log rolling

### ISSUE THREAD

**Issue by LDNail** [carbonblack/cb-event-forwarder#171]
Can switches/config options be added to roll logs based on time interval or file size... 

OR 

Switch to using logrotate.d

**Comment by nguyenl95** [comment]
Yes I'm also experiencing bugs related to this problem. Whenever I split the main log by logrotate, cb-event-forwarder couldn't append log to the new file. This means service is not working properly without any notifications.

**Comment by zacharyestep** [comment]
Added a feature that rolls logs into the service, you should not have to log-rotate anymore.
