### ISSUE TITLE
Feed hits do not include the "title" field from the feed

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#18]
The feed hit provided by Carbon Black over the event bus does not include the "title" from the feed report. That context would be extremely useful for Splunk and other SIEM integrations.

Technically this is challenging because that would require interacting asynchronously with the Cb REST API - we currently don't even need an API key for the event-forwarder to function. Events would have to be enqueued locally and the title retrieved from the feed document before they could be emitted as output.

**Comment by askthedragon** [comment]
This has been addressed by a198e2f971fb425f24ee2d102464b7f7476f0556
