### ISSUE TITLE
Allow S3 configuration to specificy a prefix (sub-folder)

### ISSUE THREAD

**Issue by asieira** [carbonblack/cb-event-forwarder#31]
Currently the S3 configuration only allows you to specify a bucket where the files will be saved, but the files are all saved with no prefix.

Please allow a configurable and optional prefix to be used for all created files, as this will give users more flexibility to store the events in non-dedicated buckets more easily.

**Comment by jjguy** [comment]
+1, obvious add in retrospect

**Comment by askthedragon** [comment]
A pull request has been added with these features!
