### ISSUE TITLE
Normalize "{remote|local}_ip", "{remote|local}_port", "protocol" in ioc_attr for LEEF output

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#40]
```
local_ip -> src
local_port -> srcPort
protocol -> proto
remote_ip -> dst
remote_port ->dstPort
```

do this for `ioc_attr` fields on feed/watchlist hits as well as `netconn` event types

**Comment by jgarman** [comment]
Link to LEEF specification: http://www.ibm.com/support/knowledgecenter/SS42VS_7.2.6/com.ibm.dsm.doc/c_LEEF_Format_Guide_predefinedAttrrs.html?lang=en

**Comment by askthedragon** [comment]
Adding sample data

{"sensor_id": 22, "group": "Default Group", "cb_server": "None", "server_name": "localhost.localdomain", "feed_id": 21, "timestamp": 1446093189.866, "hostname": "W7-LOW", "report_score": 25, "feed_name": "threatexchangeconnector", "ioc_value": "tvrain.ru", "computer_name": "W7-LOW", "cb_version": "5.1.0.150625.0500", "process_guid": "00000016-0000-06f4-01d1-17155e4ba159", "os_type": "Windows", "ioc_attr": {"direction": "Outbound", "protocol": "TCP", "local_ip": "192.168.230.131", "dns_name": "tvrain.ru", "remote_port": 22, "local_port": 49224, "port": 22, "remote_ip": "178.248.236.23"}, "type": "feed.ingress.hit.process", "ioc_type": "dns", "report_id": "txid-info-Facebook-Administrator"}

{"sensor_id": 22, "group": "Default Group", "cb_server": "None", "server_name": "localhost.localdomain", "feed_id": 21, "timestamp": 1446093189.866, "hostname": "W7-LOW", "report_score": 25, "feed_name": "threatexchangeconnector", "ioc_value": "tvrain.ru", "computer_name": "W7-LOW", "cb_version": "5.1.0.150625.0500", "process_guid": "00000016-0000-06f4-01d1-17155e4ba159", "os_type": "Windows", "ioc_attr": "{\"direction\": \"Outbound\", \"protocol\": \"TCP\", \"local_ip\": \"192.168.230.131\", \"dns_name\": \"tvrain.ru\", \"remote_port\": 22, \"local_port\": 49224, \"port\": 22, \"remote_ip\": \"178.248.236.23\"}", "type": "feed.ingress.hit.process", "ioc_type": "dns", "report_id": "txid-info-Facebook-Administrator"}
