### ISSUE TITLE
Compress output files

### ISSUE THREAD

**Issue by asieira** [carbonblack/cb-event-forwarder#41]
Create a configuration option that will compress the output files and add corresponding file extensions (.gz for gzip, for example).

**Comment by jgarman** [comment]
Closing this for now. This is best handled by an external program, for example, `logrotate` which is included in many Linux distributions.

**Comment by asieira** [comment]
If the files are being written to S3 directly from the exporter, how would log rotate be able to compress the logs?

**Comment by askthedragon** [comment]
I believe you could use something like s3fs

**Comment by asieira** [comment]
How exactly would using s3fs help in ensuring files are _compressed_ before they are uploaded to S3? Looking at the [s3fs GitHub repo](https://github.com/s3fs-fuse/s3fs-fuse) I saw no mention of compression whatsoever.

**Comment by askthedragon** [comment]
Mount the s3 volume using s3fs.  Set the event forwarder to output to a file, then use log rotate to manage/compress the logs.

**Comment by jgarman** [comment]
I didn't realize that you were talking about S3 output (I was assuming file). There could be a use case for that- I'll reopen with the comment about compressing on S3 output type.

**Comment by asieira** [comment]
Yes, I forgot to make the fact that I am focused on the S3 output clear. Sorry about that.

However, if I read the code correctly the exporter is first saving batches of events to disk and then copying each local file to S3. So IMHO it would make sense to implement [streaming compression](https://golang.org/pkg/compress/gzip/#NewWriter) when the file is originally written to disk, and allow that for both file and S3 outputs. 

This would have the additional advantage of reducing the I/O load on the exporter machine and reducing the amount of temporary local disk space needed exporting large volumes of events to S3.
