### ISSUE TITLE
Source and destination IPs messed up for netconn events

### ISSUE THREAD

**Issue by adamsmutnicki** [carbonblack/cb-event-forwarder#51]
It seems that source and destination IPs are messed up for netconn events. For a following LEEF:
LEEF:1.0|CB|CB|5.1|ingress.event.netconn|cb_server=cbserver computer_name=HOSTNAME direction=inbound domain= dst=IP.180 dstPort=41447 event_type=netconn ipv4=IP.180 link_process=https://CB-SERVER/#analyze/00000014-0000-0ccc-01d1-85424831d984/1 local_ip=IP.243 local_port=443 md5=3A31ECC4DD96E63D4193FD13CE2233C3 pid=3276 port=443 process_guid=00000014-0000-0ccc-01d1-85424831d984 proto=6 protocol=6 remote_ip=IP.180 remote_port=41447 sensor_id=20 src=IP.243 srcPort=443 timestamp=1469447484 type=ingress.event.netcon

HOSTNAME has local IP .243
epoch from LEEF: 1469447484 -> Mon, 25 Jul 2016 11:51:24 GMT

According to above LEEF, and QRadar is parsing this in the same way, this is a connection which source is .243/443 while destination (marked as remote) is .180/41447. Which by itself is causing suspicions, as this should have different direction. .243 is a server listening on tcp/443. 

I managed to find this event in GUI, screenshot is attached.

Screenshot confirms that the connection was from .180 to .243, which is correct direction. 
![ev-forwarder-bug](https://cloud.githubusercontent.com/assets/20642441/17102569/8a3025b6-527a-11e6-8b7d-0ae50cdf07fb.png)

I'm seeing hundreds of such events with broken direction. 

Is there a chance to use dst IP instead on remote IP, to avoid confusion?

**Comment by jgarman** [comment]
Yes, I will assign this as a bug. I'll take a look at it this week.

Thanks

**Comment by jgarman** [comment]
fixed in 3.2.2
