### ISSUE TITLE
Feed hits with blank comms_ip and interface_ip

### ISSUE THREAD

**Issue by jgajek** [carbonblack/cb-event-forwarder#54]
Feed hit events often have comms_ip and interface_ip fields that are both blank.  Is this intended behavior or a bug?

**Comment by jgarman** [comment]
Unfortunately it looks like (and this is confirmed by running a `grep -R -i comms_ip tests/raw_data/feed*` command) that the Cb Response server sends blank `comms_ip` and `interface_ip` fields as part of the `feed` notification messages.

The `watchlist` notifications, on the other hand, do contain values in these fields. This looks like a bug in the Cb Response product itself.
