### ISSUE TITLE
Building the packages failes with error message

### ISSUE THREAD

**Issue by txwikinger** [carbonblack/cb-event-forwarder#57]
Trying to build the package fails with the following errors:

./pb_message_processor.go:17: undefined: sensor_events.CbEventMsg
./pb_message_processor.go:31: undefined: sensor_events.CbEventMsg

**Comment by jgarman** [comment]
Run "go generate ./..." - see https://github.com/carbonblack/cb-event-forwarder/blob/master/Makefile#L14

**Comment by jgarman** [comment]
Were you able to build this? Just going through and cleaning up tickets

**Comment by jgarman** [comment]
No response - autoclosing
