### ISSUE TITLE
Documentation of JSON event fields

### ISSUE THREAD

**Issue by asieira** [carbonblack/cb-event-forwarder#63]
I have found that https://github.com/carbonblack/cb-event-forwarder/blob/master/EVENTS.md only provides detailed documentation of the fields and respective formats for the LEEF format only. 

Is it possible to provide similar field by field documentation for the JSON format, or if exists perhaps include a link to it?

**Comment by jgarman** [comment]
We have some documentation here on the server-generated events: https://developer.carbonblack.com/reference/enterprise-response/event-forwarder/event-schema/
