### ISSUE TITLE
Include process path in JSON events

### ISSUE THREAD

**Issue by asieira** [carbonblack/cb-event-forwarder#64]
Reading https://github.com/carbonblack/cb-event-forwarder/blob/master/EVENTS.md I've noticed that the LEEF format includes the process path and command line invocation, but observing the JSON events those fields are not present.

Is it possible to include (perhaps optionally for backwards compatibility) into the JSON events?

**Comment by johntmyers** [comment]
For what events? I'm currently testing with `watchlist.hit.process` and I have path information showing up just fine.

What doesn't match up is that the information in the events are actually sub-documents within the `docs` array, which does *not* match up w/ the EVENTS.md documentation.

I'm on 5.2.

```
2016-11-08 11:50:37,140:INFO:efflux.helpers.carbonblack:{u'server_name': u'ip-172-31-30-46.ec2.internal', u'docs': [{u'process_md5': u'fd902835deaef4091799287736f3a028', u'sensor_id': 2, u'filtering_known_dlls': False, u'modload_count': 68, u'parent_unique_id': u'00
000002-0000-0ce8-01d2-39c1eb2925c0-00000001', u'cmdline': u'wmic  /node:10.10.4.50 process get commandline', u'last_update': u'2016-11-08T16:39:47.821Z', u'id': u'00000002-0000-0a68-01d2-39deb7ca765e', u'parent_name': u'cmd.exe', u'parent_md5': u'0000000000000000000
00000000000', u'group': u'Default Group', u'hostname': u'WIN7HRTESTING', u'filemod_count': 0, u'start': u'2016-11-08T16:39:47.618Z', u'comms_ip': -2108343733, u'regmod_count': 0, u'interface_ip': 168428860, u'process_pid': 2664, u'username': u'BETTERGREENCO\\john',
u'process_name': u'wmic.exe', u'emet_count': 0, u'path': u'c:\\windows\\system32\\wbem\\wmic.exe', u'netconn_count': 1, u'parent_pid': 3304, u'crossproc_count': 6, u'segment_id': 1, u'host_type': u'workstation', u'processblock_count': 0, u'os_type': u'windows', u'ch
ildproc_count': 0, u'unique_id': u'00000002-0000-0a68-01d2-39deb7ca765e-00000001'}], u'event_timestamp': 1478623807.91, u'watchlist_id': 236, u'highlights': [{u'name': u'PREPREPREwmic.exePOSTPOSTPOST', u'ids': [u'00000002-0000-0a68-01d2-39deb7ca765e-00000001']}, {u'
name': u'c:\\windows\\system32\\wbem\\PREPREPREwmic.exePOSTPOSTPOST', u'ids': [u'00000002-0000-0a68-01d2-39deb7ca765e-00000001', u'00000002-0000-0a68-01d2-39deb7ca765e-00000001']}], u'cb_version': u'5.2.0.161004.1206', u'watchlist_name': u'WMIC with Remote Connectio
ns'}
{'content_type': u'application/json'}
{'consumer_tag': u'None1', 'redelivered': False, 'routing_key': u'watchlist.hit.process', 'delivery_tag': 3, 'exchange': u'api.events'}
```

**Comment by asieira** [comment]
I'm sorry, I didn't specify that I was focused on `ingress.event.netconn` events:
```
{"cb_server":"xxxxxxx","computer_name”:"xxxxxxxx","direction":"outbound","domain":"","event_type":"netconn","ipv4":”172.16.x.x","local_ip":"0.0.0.0","local_port":0,"md5":"7B6E55B20380480EF9C52E64xxxxxxxx","pid":1518,"port":1444,"process_guid":"00000792-0000-xxxx-xxxx-26fbb265d9d6","protocol":17,"remote_ip":”172.16.x.x","remote_port":1444,"sensor_id":1938,"timestamp":1476597118,"type":"ingress.event.netconn”}
```

I also found it rather unexpected that `local_ip` and `remote_ip` were equal, but `direction` said this was an `outbound` event.

**Comment by johntmyers** [comment]
What OS is this event from? Your local_ip is 0.0.0.0, which is not equal to the remote_ip.

Also the data your looking for is partially available in the raw protobuf header. You may have better luck attaching directly to the RabbitMQ port and pulling what you need out of the protobufs. The process path information is at least available in the protobuf header.
(https://github.com/carbonblack/cbapi/blob/master/server_apis/python/example/subscribe_all.py)

Per their protobuf spec, the header is required for all messages.
https://github.com/carbonblack/cbapi/blob/master/server_apis/proto/sensor_events.proto
