### ISSUE TITLE
OS X netconn events, local_ip field

### ISSUE THREAD

**Issue by johntmyers** [carbonblack/cb-event-forwarder#71]
Using the latest OS X sensor, the `local_ip` field of exported netconn events appears to not have its endianness "fixed" before converting to a dotted decimal string, example output from a record that was exported to S3 using the latest event forwarder and latest OS X sensor:

```
{u'cb_server': u'cbserver',
  u'computer_name': u'effluxmini2.local',
  u'direction': u'inbound',
  u'domain': u'',
  u'event_type': u'netconn',
  u'ipv4': u'8.8.8.8',
  u'local_ip': u'55.3.0.10',   <---- BACKWARDS
  u'local_port': 24667,
  u'md5': u'5D3C79EEB4FD77EDFEB1AA6FDB7D82C9',
  u'pid': 804,
  u'port': 24667,
  u'process_guid': u'00000011-0000-0324-01d2-56f7f5883e12',
  u'protocol': 17,
  u'remote_ip': u'8.8.8.8',
  u'remote_port': 53,
  u'sensor_id': 17,
  u'timestamp': 1483689948,
  u'type': u'ingress.event.netconn'}
```

**Comment by johntmyers** [comment]
On second look, this is probably a sensor issue.

Same issue is in the UI.

![image](https://cloud.githubusercontent.com/assets/9696606/21777950/45774b9c-d66f-11e6-894d-d416f77d709b.png)

**Comment by askthedragon** [comment]
Thanks for reporting this.  I am in contact with our engineering team for a potential fix

**Comment by askthedragon** [comment]
closing this, since this isn't a problem with the event-forwarder, but with the sensor.
