### ISSUE TITLE
Include "score" and "description" with feed hits

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#81]
We currently pull the feed "title" from the report associated with feed hits - add the "score" and "description" fields as well.

**Comment by zacharyestep** [comment]
if reflect.TypeOf(feedId).Kind() == reflect.String &&
					reflect.TypeOf(reportId).Kind() == reflect.String {
					iFeedId, err := feedId.(json.Number).Int64()
					if err == nil {
						/*
						 * Get the report_title for this feed hit
						 */
						reportTitle, reportScore, err := GetReport(int(iFeedId), reportId.(string))
						log.Printf("Report title = %s , Score = %s",reportTitle, reportScore)
						if err == nil {
							/*
							 * Finally save the report_title into this message
							 */
							msg["report_title"] = reportTitle
							msg["report_score"] = reportScore
							/*
							log.Printf("report title,score for id %s:%s == %s,%s\n",
								feedId.(json.Number).String(),
								reportId.(string),
								reportTitle,
								reportScore)
								*/
						}

					} else {
						log.Println("Unable to convert feed_id to int64 from json.Number")
					}

**Comment by zacharyestep** [comment]
This went live in 340
