### ISSUE TITLE
init script is overwritten upon event-forwarder upgrade

### ISSUE THREAD

**Issue by adamnadrowski** [carbonblack/cb-event-forwarder#83]
The cb-event-forwarder upgrade process currently overwrites /etc/init/cb-event-forwarder.conf upon an upgrade. Since /etc/init/cb-event-forwarder.conf is commonly modified when running multiple instances of event-forwarder, we should generate an rpmnew instead of overwriting it.

**Comment by zacharyestep** [comment]
I believe we have done as best as we can given the function of init.d and rpm utils.
