### ISSUE TITLE
Installing on Redhat system

### ISSUE THREAD

**Issue by ryenshaie1** [carbonblack/cb-event-forwarder#86]
Hello,

Is it possible to install the cb-event-forwarder application on a Redhat instance? I successfully installed and configured it, but cannot use the initctl command to start the service. I am just curious if this service is compatible with RHEL 7.

Thank you!

Ryan

**Comment by zacharyestep** [comment]
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Services.html

RHEL7 has moved on from intitctl to systemctl. Let me see if I can get write service files that will work for you.

**Comment by zacharyestep** [comment]
Ryan,

Please try the following : 

`cd /etc/system/systemd`

Add a file called cb-event-forwarder.service with these contents:
[Unit]
Description= Carbon Black Event Forwarder
Documentation=http://github.com/carbonblack/cb-event-forwarder
After=network.target

[Service]
Type=simple
WorkingDirectory=/usr/share/cb/integrations/event-forwarder
ExecStart=/usr/share/cb/integrations/event-forwarder/cb-event-forwarder /etc/cb/integrations/event-forwarder/cb-event-forwarder.conf &>/var/log/cb/cb-event-forwarder.log

[Install]
WantedBy=multi-user.target

`systemctl daemon-reload`
`systemctl enable cb-event-forwarder`
`systemctl start cb-event-forwarder`

**Comment by n2N8Z** [comment]
Shell redirection in service unit files has no effect, and so in the example above, cb-event-forwarder.log does not get written.

To redirect STDOUT and STDERR in a service unit files, you have to use the StandardOutput and
StandardError configuration options respectively.

The defaults for these options are defined in /etc/systemd/system.conf, and on my CentOS 7.3 system they are #DefaultStandardOutput=journal, and #DefaultStandardError=inherit.

StandardError=inherit means that it will use the same file descriptor as StandardOutput, so using the defaults, STDERR also goes to journal.

So using the example service unit file above, the Cb Event Forwarder STDOUT and STDERR logs both go to the journal.

# https://www.freedesktop.org/software/systemd/man/systemd.exec.html
