### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by n2N8Z** [carbonblack/cb-event-forwarder#89]
The debug option in the configuration file bridge section, which has the comment "enable extra debugging output", is used to set config.DebugFlag to true, but DebugFlag is never referenced again.
The command line debug switch sets the debug variable, which enables the http://%s:%d/debug/sendmessage end point.
Neither option affects the logging level.

./tests/scripts/cbeventforwarder/bridge.py however does use this option to set its logging level.

**Comment by jgarman** [comment]
Yes, this is true... that configuration option is an artifact left over from the previous python-based event forwarder. We should improve the logging situation - is there something specifically that you would like to see in the debug logs?

**Comment by n2N8Z** [comment]
Have no specific requirements at the moment.
Depending on the debug level selected, it would be good to be able to see messages received and sent.
TLS debugging information.

**Comment by jgarman** [comment]
A debug log has been added to 3.4.0 of the event forwarder. Are you seeing TLS errors when interoperating with certain endpoints?

**Comment by n2N8Z** [comment]
No, that was just and idea for something that might be useful.

**Comment by zacharyestep** [comment]
Going to close this since debug mode works. Add another issue for specific debug logging.
