### ISSUE TITLE
Cannot retrieve fileCatalog.publisher

### ISSUE THREAD

**Issue by jbmfg** [carbonblack/cb-event-forwarder#93]
When requesting fileCatalog.x you get the x field that the fileCatalog makes available.  However, when you try to access fileCatalog.publisher you get an empty response from cbapi.protection.models.Publisher :

`    comps = api.select(Computer).where("deleted:false")
    for c in comps:
        files = c.fileInstances.where("fileName:winscp.exe")
        for f in files:
            print f.fileCatalog.company # returns the expected company field
            print f.fileCatalog.publisher # returns cbapi.protection.models.Publisher:
`

**Comment by askthedragon** [comment]
Put this under the cbapi-python bindings.  This issue doesn't have to do with the event forwarder.
