### ISSUE TITLE
Add feed report URL to feed events

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#95]
We currently augment feed events with title and score from the feed report. Add the report URL to this list.

**Comment by BruteFarcical** [comment]
This would be very useful as feeds such as bit9endpointvisibility already have good write-ups for the IOCs but this would also allow for good URL capabilities for custom threat intel feeds written by customers and/or MSSPs.

**Comment by jgarman** [comment]
Let's fold this into a minor release - 3.4.1?

**Comment by BruteFarcical** [comment]
@zacharyestep was this rolled into 3.4.1 or 3.4.2?

No worries if not, but do you have an ETA for what version it might be included in?

**Comment by zacharyestep** [comment]
CODE in dev_feed_report_url , fodling into next release
