### ISSUE TITLE
Remove `highlights_by_doc` field from watchlist/feed hits

### ISSUE THREAD

**Issue by jgarman** [carbonblack/cb-event-forwarder#96]
This field can become quite sizable and clutters log files/ingest pipelines. Add a tunable to turn it off if wanted.

**Comment by zacharyestep** [comment]
Code added in "dev_suprsess_highlights" branch

**Comment by jgarman** [comment]
(pull request #98)

**Comment by jgarman** [comment]
Fixed in 3.4.4.
